# Generated by Django 2.2.5 on 2020-03-26 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_auto_20200312_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='baths',
            field=models.IntegerField(help_text='객실의 화장실 수를 적어주세요.'),
        ),
        migrations.AlterField(
            model_name='room',
            name='bedrooms',
            field=models.IntegerField(help_text='객실의 침실 수를 적어주세요.'),
        ),
        migrations.AlterField(
            model_name='room',
            name='beds',
            field=models.IntegerField(help_text='객실의 침대 수를 적어주세요.'),
        ),
        migrations.AlterField(
            model_name='room',
            name='guests',
            field=models.IntegerField(help_text='객실에 머무를 수 있는 총 인원 수를 적어주세요.'),
        ),
    ]
